apiVersion: batch/v1
kind: Job
metadata:
  name: dd-wa-gat-simple-trial1
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: dd-wa-gat-simple-trial1
    spec:
      restartPolicy: Never
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - "NVIDIA-GeForce-RTX-3090"
      containers:
      - name: pytorch-gpu-container
        image: gitlab-registry.nrp-nautilus.io/dimademler/wa-dataset:latest  
        command: ["/bin/bash", "-c"]
        args:
          - |
            {
              # Update package lists and install unzip
              apt-get update && apt-get install -y unzip
              

              cd /dima-pvc/wa-dd-prediction-model/
              # cd ../../dima-pvc/wa-dd-prediction-model/
                            
              # Run the global search for all model types
              python y_02_GAT_simple_trial1.py
            } 2>&1 | tee /dima-pvc/wa-dd-prediction-model/logs/y_02_GAT_simple_trial1.log  
        resources:
          limits:
            memory: 16Gi
            cpu: 5
            nvidia.com/gpu: 1
          requests:
            memory: 14Gi
            cpu: 5
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /dima-pvc
          name: dima-pvc
      volumes:
        - name: dima-pvc
          persistentVolumeClaim:
            claimName: pvc2-dmitridemler