apiVersion: batch/v1
kind: Job
metadata:
  name: dd-wa-dataset-run
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: dd-wa-dataset-run
    spec:
      restartPolicy: Never
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - "NVIDIA-GeForce-RTX-3090"
      containers:
      - name: pytorch-gpu-container
        image: gitlab-registry.nrp-nautilus.io/dimademler/wa-dataset:latest  #Change this to the correct new image
        command: ["/bin/bash", "-c"]
        args:
          - |
            {
              cd ../dima-pvc/wa-dd-prediction-model/
              
              # Print environment variables for debugging
              env
              
              # Run the global search for all model types
              python gnn_try4_GAT.py
            } 2>&1 | tee /dima-pvc/wa-dd-prediction-model/logs/May27_GAT4.log  
        resources:
          limits:
            memory: 11Gi
            cpu: 8
            nvidia.com/gpu: 1
          requests:
            memory: 10Gi
            cpu: 8
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /dima-pvc
          name: dima-pvc
      volumes:
        - name: dima-pvc
          persistentVolumeClaim:
            claimName: pvc2-dmitridemler