apiVersion: v1
kind: Pod
metadata:
  name: dd-tprobe-pod
spec:
  containers:
  - name: dd-mypod
    image: ubuntu
    command: ["/bin/bash"]
    args: ["-c", "apt-get update && apt-get install -y vim nano git && cd /dima-pvc/wa_hls4ml_models/ && sleep infinity"]
    resources:
      limits:
        memory: 500Mi
        cpu: 300m
      requests:
        memory: 400Mi
        cpu: 300m
    volumeMounts:
    - mountPath: /dima-pvc
      name: dima-pvc
  volumes:
    - name: dima-pvc
      persistentVolumeClaim:
        claimName: pvc2-dmitridemler
